# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mJZRxJGJmvH-kvzDhz-7DzW-BEAnssjC
"""

import pandas
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from pandas import DataFrame

data=pandas.read_csv('car.csv')

data.describe(
)

X=DataFrame(data,columns=['km_driven'])
y=DataFrame(data,columns=['selling_price'])

plt.scatter(X,y,alpha=0.3)
plt.title('Selling price vs kms driver  (car dekho)')
plt.xlim(0,810000)
plt.ylim(0,8900000)
plt.xlabel('kms_driven')
plt.ylabel('selling price')
plt.show()

regression=LinearRegression()

regression.fit(X,y)



plt.figure(figsize=(20,10))
plt.scatter(X,y,alpha=0.3)

plt.title('Selling price vs kms driver  (car dekho)')
plt.xlim(0,810000)
plt.ylim(0,8900000)
plt.xlabel('kms_driven')
plt.ylabel('selling price')
plt.plot(X,regression.predict(X),  color='red',  linewidth=5)
plt.show()

